Intents
csacro/Alexa-Skill-Emotionsadaptivitaet-im-Small-Talk pull request #8
Opened 2019-06-29 19:30 UTC by aai38

Hab jetzt bei mir kurz des .js gelöscht, weil mans nicht automatisch mergen konnte und der Code ist noch gar nicht getestet, also sind bestimmt noch viele Fehler drin

2019-07-01 08:05 UTC, csacro commented
Der Tippfehler in der Datenbank-Methode war in deinem Branch noch nicht korrigiert und hätte zu Fehlern bei der Ausführung geführt. Habe das schnell gefixt.
@aai38: Bitte mit der verbesserten Version testen :)

2019-07-02 07:16 UTC, csacro commented
Jetzt sollte es immer nur eine Verbindung zur Datenbank geben.

Bezüglich des hallo.json Files (Tippfehler im Commit): Du hast das vermutlich beim mergen mit dem master "zerstört". Ich habe UserIntent und SuggestionIntent copy paste hinzugefügt.
@aai38 : bitte schau da doch nochmal drüber, dass alles passt
Was ich mich noch frage: Wofür sind in hallo.json die Zeilen ab 849? Wenn ich diesen letzten Block nicht lösche funktioniert bei mir BuildModel nicht.

2019-07-02 09:19 UTC, csacro requested changes
Damit es zu keinen Verwirrungen kommt hier mein aktuelles Fazit (alle vorherigen Kommentare können ignoriert werden)

zum hallo.json File
Komma-Fehler sind ausgebessert
@aai38 schaue bitte, dass das hallo.json File stimmt (vermutlich hast du das beim Mergen mit dem master "zerstört")
UserIntent und SuggestionIntent sind bereits copy paste hinzugefügt
@aai38 Wofür sind in die Zeilen ab 849? Wenn ich diesen letzten Block nicht lösche funktioniert bei mir BuildModel nicht. (Block ist aktuell noch drin)

zum hallo.py File
sobald UserFeeling gesetzt werden soll, stürtzt es bei mir ab

zur Anzahl der Datenbankverbindungen
konnte ich doch nicht fixen: aus irgendeinem Grund (keine Ahnung wieso) werden immer zwei Verbindungen statt einer aufgebaut

2019-07-02 10:01 UTC, aai38 commented
Ich denke, es hat mir echt das .json zerschossen beim mergen, ich kann meins ganz normal builden. Der letzte Block kann raus, weiß gar nicht wie der überhaupt reingekommen ist, ist nur damit man eine Confirmation hat, aber das brauchen wir bei uns nicht

2019-07-02 10:23 UTC, csacro commented
Aber ich weiß nicht ob mein json vollständig ist/war.
Habe wie gesagt nur schnell die beiden Intents eigefügt, damit ich es mal laufen lassen konnte

2019-07-02 10:41 UTC, aai38 commented
Hab jetzt die .json nochmal verglichen und den Rest hinzugefügt, sollte jetzt eigentlich passen.

2019-07-04 16:58 UTC, csacro approved these changes

2019-07-04 17:02 UTC, merged